"""initial_schema_with_auth_and_indexes

Revision ID: 7b78c9a66753
Revises: 
Create Date: 2026-02-28 21:24:24.455618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b78c9a66753'
down_revision: Union[str, None] = '0001_create_base'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planned_payments', 'paid_rub',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('ix_txn_cashflow2', 'transactions', ['is_cashflow2'], unique=False)
    op.create_index('ix_txn_cashflow_unassigned', 'transactions', ['is_cashflow2', 'cat_lvl1_2'], unique=False)
    op.create_index('ix_txn_cp_key', 'transactions', ['cp_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txn_cp_key', table_name='transactions')
    op.drop_index('ix_txn_cashflow_unassigned', table_name='transactions')
    op.drop_index('ix_txn_cashflow2', table_name='transactions')
    op.alter_column('planned_payments', 'paid_rub',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
